# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foo',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
